### ISSUE TITLE
gmmk pro rev 1 ansi rotary encoder backwards

### ISSUE THREAD

**Issue by hardpoorcorn** [SRGBmods/QMK-Binaries#11]
The encoder in this firmware registers clockwise rotation as volume decrease, counter-clockwise rotation as volume increase.  This is opposite of expected behavior.

https://github.com/SRGBmods/QMK-Binaries/blob/main/QMK%2BVIA-Firmware/0.21.6/gmmk_pro_rev1_iso_via.bin

**Comment by naitoshedo** [comment]
Even though this should be changeable in VIA, I updated that firmware's encoder directions in source now.
