### ISSUE TITLE
How to open the compatibility mode need

### ISSUE THREAD

**Issue by aihk** [SRGBmods/QMK-Binaries#13]
`void signalrgb_mode_enable(void)
{
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SIGNALRGB); //Set RGB Matrix to SignalRGB Compatible Mode
}`
How to open the compatibility mode need

**Comment by naitoshedo** [comment]
What? I not only provide the full source https://docs.signalrgb.com/qmk/building-firmware-from-source but a directory https://github.com/SRGBmods/QMK-Binaries/tree/main/GPL for hand patching the SRGB protocol into any QMK fork (rgb_matrix is required and you may have to back port functions from that from mainline.)
