### ISSUE TITLE
Split keyboard problem

### ISSUE THREAD

**Issue by aihk** [SRGBmods/QMK-Binaries#14]
How to write the JS file of Split Keyboard? Still do not support split files

**Comment by naitoshedo** [comment]
Even when split technically it's still columns and rows for the LEDs. So you need to pad the width of the device and then skip some columns to equal the split space.

**Comment by aihk** [comment]
However, I can only control the RGB on the left through SignalRGB, and the RGB on the right cannot be controlled

**Comment by naitoshedo** [comment]
I would hit up the Test Plugin server's QMK channels so faster communication can occur https://discord.com/invite/J5dwtcNhqC go to #roles there and pick the QMK role. Then ask in #need-help there.
