### ISSUE TITLE
Plugin repository?

### ISSUE THREAD

**Issue by tre4b** [SRGBmods/QMK-Binaries#15]
Is there a place to put plugins created specifically for a type of keyboard?  I downloaded the firmware from here and modified the .JS files and wanted to upload them somewhere incase another user of the same keyboard wanted them so they don't have to duplicate the effort.

**Comment by naitoshedo** [comment]
Yes I moved the plugin repo to a standalone repo so I can be loaded directly from inside of SignalRGB now:
https://github.com/SRGBmods/qmk-plugins
