### ISSUE TITLE
Keychron Q1 does‘t work in POST

### ISSUE THREAD

**Issue by einbequemesbrot** [SRGBmods/QMK-Binaries#16]
During Startup I can no longer use the Keyboard to get into BIOS or change the selection in my boot loader. 
In the OS everything (including Signal RGB Control of the LEDs and remapping the keys in VIA) works perfectly fine.

**Comment by naitoshedo** [comment]
I have compiled all firmware for Keychron to have NKRO enabled by default, Function Key + N turns this off and allows access to BIOS and other low level interfaces.
