### ISSUE TITLE
KVM hotkey not working - Redragon K556 binary

### ISSUE THREAD

**Issue by boyestrous** [SRGBmods/QMK-Binaries#17]
Howdy! I recently flashed my Redragon k556 keyboard with the firmware found here: https://docs.signalrgb.com/qmk/supported-keyboards

After the flash, I'm no longer able to use my hotkeys on+ my KVM switch. Typically I would use the following to switch back-and-forth:
- double tap CTRL or the Windows Key, then 1 (for left PC) or 2 (for right PC)

I'm totally new to this, but I found this discussion:
[Level 1 Techs Forum](https://forum.level1techs.com/t/solved-qmk-and-1-4-display-port-kvm-switch/173526) - they said to Disable NKRO by putting `NKRO_ENABLE = no` in rules.mk

I see the [README instructions for making my own binary from source](https://docs.signalrgb.com/qmk/building-firmware-from-source), but I don't want to start from scratch. Is there a way to start with an existing binary, but tweak a few of the settings and recompile?

**Comment by naitoshedo** [comment]
I would reach out to @TheDordo about this issue as they know more about the redragon boards compared to me. https://discord.com/channels/951628333504925756/1115823662688374845
