### ISSUE TITLE
Keychron K2 Pro ISO not working from 0.14.29-keychron with VIA

### ISSUE THREAD

**Issue by pherting** [SRGBmods/QMK-Binaries#18]
Hello, i try to flash my Keychron K2 Pro ISO with the keychron_k2_pro_iso_rgb_via.bin
After this my Enter and # Key are swapped and i cant connect over Chrome VIA to the Keyboard.
The SignalRGB Plugin and the Keyboard self are running good except the two swapped keys.

I try it also with the Design Tab and the k2_pro_iso_rgb_v1.1.json from Keychron Website, but i get only the error
"fetching v3 definition failed" or
"received invalid protocol version from device"

Has anyone maybee some tipps what i can try or a working bin for my K2 Pro ISO DE Layout?

Thanks a lot!

**Comment by naitoshedo** [comment]
Perhaps https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k2_pro/via_json may be more recent in comparison to the website version.

**Comment by pherting** [comment]
Thank you very much @naitoshedo !
It's working ;)

I write you on Discord a PN for the js Plugin what i make for the K2 Pro ISO DE.
So you can add it to the repo ;)

**Comment by naitoshedo** [comment]
I do not accept DMs on Discord, you can upload it here as a response to this comment or the SignalRGB Plugin Test Discord Server: https://discord.com/channels/951628333504925756/1078865090964639784

**Comment by pherting** [comment]
[Keychron_K2_Pro_QMK_ISO_DE_Keyboard.zip](https://github.com/SRGBmods/QMK-Binaries/files/12884356/Keychron_K2_Pro_QMK_ISO_DE_Keyboard.zip)

Ok perfect, thanks a lot ;)
