### ISSUE TITLE
keychron Q1 pro not recognise

### ISSUE THREAD

**Issue by MaximeProulx** [SRGBmods/QMK-Binaries#19]
After flashing the keyboard with the right bin and putting the right plugin signal RGB still not recognise my keychron q1 pro as a supported device.
I know I am doing the right specs because it's working fine with my keychron k2 pro

**Comment by naitoshedo** [comment]
I compiled more recent bluetooth playground firmware and replaced the previous versions, let me know if this helps.

**Comment by MaximeProulx** [comment]
Yes I can now see my Q1 pro on signal thanks

**Comment by 422415** [comment]
I flashed the 0.14.29 Q1 Pro ANSI firmware and the lighting does work with SignalRGB. However when I try to connect to the keyboard with the VIA windows app or the website usevia.app I get this error:

Fetching v3 definition failed
Device: Keychron Q1 Pro
Vid: 0x3434
Pid: 0x0610

I have made sure to have SignalRGB turned off before trying to connect but still comes up with this error.
