### ISSUE TITLE
GMMK Numpad bluetooth

### ISSUE THREAD

**Issue by vjt4** [SRGBmods/QMK-Binaries#20]
What is the discoverability button after updating firmware to "gmmk_numpad_default" found on this repo, thanks!

**Comment by naitoshedo** [comment]
If you want to use Bluetooth you lose SignalRGB compatibility: As stated directly from QMK mainline: [Broken](https://github.com/qmk/qmk_firmware/tree/master/keyboards/gmmk/numpad#broken)
Bluetooth functionality. If they ever fix this I will of course create a new build.
