### ISSUE TITLE
Q1 Pro Right Arrow Key Not controlled by Signal

### ISSUE THREAD

**Issue by powershellbreakfast** [SRGBmods/QMK-Binaries#26]
Q1 Pro Right Arrow Key Not controlled by Signal, I flashed the newest Bin file and signal is able to control all but the right arrow key

**Comment by naitoshedo** [comment]
Sounds like the LED count in arrays doesn't match the actual keyboard so the plugin should be reviewed: (Plugins available here) https://github.com/SRGBmods/qmk-plugins/tree/main/Keychron
