### ISSUE TITLE
GMMK Numpad

### ISSUE THREAD

**Issue by RustedAperture** [SRGBmods/QMK-Binaries#3]
Just wondering if you can share the source files for the gmmk numpad with via. I cannot find the source for these files anywhere and it would be a great help.

**Comment by naitoshedo** [comment]
Source can be found via the gmmk_numpad branch of the GloriousThrall (official repo): https://github.com/GloriousThrall/qmk_firmware/tree/gmmk_numpad

**Comment by RustedAperture** [comment]
@naitoshedo thank you I ended up building a profile for vial based on that!
