### ISSUE TITLE
Support for Lemokey P1 & P1 Pro

### ISSUE THREAD

**Issue by Lyte-vb** [SRGBmods/QMK-Binaries#30]
Please help with firmware for lemokey P1 & P1 Pro keyboards.

**Comment by naitoshedo** [comment]
Source code is not available yet... Once it is I will do so.

**Comment by Lyte-vb** [comment]
Source code is available now. 
https://github.com/Keychron/qmk_firmware/tree/playground/keyboards/lemokey/p1
