### ISSUE TITLE
Support for Lemokey P1 & P1 Pro

### ISSUE THREAD

**Issue by Lyte-vb** [SRGBmods/QMK-Binaries#31]
The source code is available now. 
https://github.com/Keychron/qmk_firmware/tree/playground/keyboards/lemokey/p1

**Comment by naitoshedo** [comment]
Added. [P1](https://github.com/SRGBmods/QMK-Binaries/tree/main/QMK%2BVIA-Firmware/0.14.29-keychron/playground), [P1 Pro](https://github.com/SRGBmods/QMK-Binaries/tree/main/QMK%2BVIA-Firmware/0.14.29-keychron/wireless_playground)

Source of course is available as well: [P1](https://github.com/SRGBmods/KeychronQMK/tree/playground), [P1 Pro](https://github.com/SRGBmods/KeychronQMK/tree/wireless_playground)

**Comment by MarkDa03** [comment]
@naitoshedo Hey - HID Configuration not found when we try to use the launcher using the above-mentioned SignalRGB Firmware. Any chance you can create a ticket compatible version one? I need to set my layouts, where i can switch between mac and windows layouts. I cant do that without having access to the launcher. I had to revert back to the original firmware. Also, signalRGB was only able to find the keyboard whilst connected with a cable, not wirelessly. 

Thanks
