### ISSUE TITLE
Please add support of Keychron V3 Max in wired mode

### ISSUE THREAD

**Issue by Nester0v** [SRGBmods/QMK-Binaries#32]
Link on keyboard: [https://www.keychron.com/products/keychron-v3-max-qmk-via-wireless-custom-mechanical-keyboard?variant=40868403183705](url)

Link on QMK repository(branch wireless_playground: [https://github.com/Keychron/qmk_firmware/tree/abefc1d4a6be3ca70fec42288d5f30896ba70a81/keyboards/keychron/v3_max](url)

I tried to make it myself - but without success

**Comment by naitoshedo** [comment]
[Pre-compiled firmware here](https://github.com/SRGBmods/QMK-Binaries/tree/main/QMK%2BVIA-Firmware/0.14.29-keychron/wireless_playground). [Source code is here](https://github.com/SRGBmods/KeychronQMK/tree/wireless_playground). I also added the user plugin just now to the qmk-plugins repo so once you flash it and restart SignalRGB it should be detected.
