### ISSUE TITLE
caps lock key is blinking when caps is off 

### ISSUE THREAD

**Issue by ItsKruml** [SRGBmods/QMK-Binaries#33]
keychron v1 iso de with encoder

firmware version: 0.26.4

the capslock key blinks white (like if the keyboard and signalrgb are conflicting between what colour to show   
https://github.com/user-attachments/assets/05b42631-f777-48b9-a479-a8bfe84a881c

SOLUTION -----------------> PRESS "fn" and "tab"

**Comment by naitoshedo** [comment]
I do post about such things, Keychron builds should be okay for VIA as `[I apply the following](https://github.com/SRGBmods/QMK-Binaries/blob/main/GPL/qmk_firmware/quantum/fix-blinking-indicators.txt)`.
