### ISSUE TITLE
Broken links on the README page

### ISSUE THREAD

**Issue by PeterMortensen** [SRGBmods/QMK-Binaries#34]
At least two links are broken on [the README page](https://github.com/SRGBmods/QMK-Binaries/blob/main/README.md):

 * [0.26.0](https://github.com/SRGBmods/QMK-Binaries/tree/main/QMK%2BVIA-Firmware/0.26.0) (two instances)
 * [04_15_2024](https://github.com/SRGBmods/QMK-Binaries/tree/main/QMK%2BVIA%2BVial-Firmware/04_15_2024)

Result:

> ***"404 - page not found"***

**Comment by naitoshedo** [comment]
Broken links addressed, thanks for the reminder.
