### ISSUE TITLE
Gmmk 2 Flickering and Wrong Color 

### ISSUE THREAD

**Issue by Lordhengi** [SRGBmods/QMK-Binaries#5]
Firmware: gmmk2_p96_iso_via.bin
Version: 0.20.1
Software: QMK Toolbox
Issue:
flickering and wrong color of the button 1.

![photo_2023-03-16_19-41-09](https://user-images.githubusercontent.com/18429612/225722483-f2394887-9795-47e9-bea3-adc82fbc19c7.jpg)

**Comment by naitoshedo** [comment]
Have you tried using the <https://raw.githubusercontent.com/SRGBmods/QMK-Binaries/main/SignalRGB-Plugins/GMMK/GMMK_2_96_ISO_QMK_Keyboard.js> plugin?

**Comment by Lordhengi** [comment]
Yes I tried and the problem persists.

**Comment by naitoshedo** [comment]
Might want to try the officially supported GMMK2 stuff then: https://docs.signalrgb.com/qmk/supported-keyboards

**Comment by Lordhengi** [comment]
I solved the problem by deleting the 120 from the vKeys.
The flickering of button 1 has stopped.

**Comment by naitoshedo** [comment]
Has this been resolved or are you waiting on additional help?
