### ISSUE TITLE
Gmmk2 Key out of sync

### ISSUE THREAD

**Issue by Lordhengi** [SRGBmods/QMK-Binaries#6]
Firmware: gmmk2_p96_iso_via.bin
Version: 0.20.1
Software: QMK Toolbox
Issue:
The left shift key and the left strg key are out of sync.
![photo_2023-03-16_19-50-38](https://user-images.githubusercontent.com/18429612/225723991-21eefd57-8848-4c48-b7a8-867d6c74372a.jpg)

**Comment by naitoshedo** [comment]
This should also be covered by #5 (more than likely a plugin issue).
