### ISSUE TITLE
I would flash keychron k3 rgb optical iso but I can find only with ansi.  Is it available? Thx you! 

### ISSUE THREAD

**Issue by ovnis82** [SRGBmods/QMK-Binaries#7]

**Comment by naitoshedo** [comment]
Pretty sure we connected on Discord but just in case the build is available here: https://github.com/SRGBmods/QMK-Binaries/blob/main/QMK%2BVIA-Firmware/0.7.101-sonix/keychron_k3_rgb_optical_iso_via_iso.bin

**Comment by ovnis82** [comment]
Hello, it seems than the file is not available. 

Do you know where I can download it? 

Thx you!

**Comment by naitoshedo** [comment]
Build is available again.
