### ISSUE TITLE
Error: device.write(): HID handle is invalid, confirm that the protocol type selected is HID.

### ISSUE THREAD

**Issue by aihk** [SRGBmods/QMK-Binaries#8]
Error: device.write(): HID handle is invalid, confirm that the protocol type selected is HID.

Software errors，

**Comment by naitoshedo** [comment]
Without any further information, (Keyboard Manufacturer & Model, what Firmware you used, etc) this is hard to help with.

**Comment by aihk** [comment]
Has been solved, thank you
